### ISSUE TITLE
Add margin to prescription summary tag

### ISSUE THREAD

**Issue by rolewest** [rolewest/healthfull#1]
The `Edit My Details` summary needs some margin or padding.
![image](https://user-images.githubusercontent.com/87285224/232632346-9a40c054-f770-468c-ac29-5bd7a51fbb35.png)

**Comment by sagar-io** [comment]
Hi @rolewest, Are you talking about these changes? 
![Screenshot 2023-04-19 2217500](https://user-images.githubusercontent.com/86215447/233146774-3b7821cd-c916-4f0f-a269-62334174e585.png)
![Screenshot 2023-04-19 221750](https://user-images.githubusercontent.com/86215447/233146790-71aceba9-721d-4287-a50e-e077bd5870ce.png)

**Comment by rolewest** [comment]
Specifically I'm referring to the left-margin/padding on the **Edit My Details** `<summary>` tag. This can be seen by going to [http://localhost:8080/#/base](http://localhost:8080/#/base) or in the code base in the file `BaseMeasure.vue` line 14
![healthfull-margin](https://user-images.githubusercontent.com/87285224/233251919-2c309636-46a3-4d3d-bc58-3fcf96b06937.png)

This won''t be visible in the browser (localhost etc.) until you have entered some data (just height, weight, and age; I believe) as  it won't show if there are no details to edit.

**Comment by rolewest** [comment]
@sagar-io Specifically I'm referring to the left-margin/padding on the **Edit My Details** `<summary>` tag. This can be seen by going to [http://localhost:8080/#/base](http://localhost:8080/#/base) or in the code base in the file `BaseMeasure.vue` line 14

This won''t be visible in the browser (localhost etc.) until you have entered some data (just height, weight, and age; I believe) as  it won't show if there are no details to edit.


![healthfull-margin](https://user-images.githubusercontent.com/87285224/233251919-2c309636-46a3-4d3d-bc58-3fcf96b06937.png)

**Comment by sagar-io** [comment]
@rolewest, Please review it. 
![Screenshot 2023-04-20 122029](https://user-images.githubusercontent.com/86215447/233284094-d8a09af9-cab7-4569-91cb-dbb14b34ead6.png)

**Comment by rolewest** [comment]
LGTM!

**Comment by rolewest** [comment]
@sagar-io Looks good to me! 
I recommend forking and cloning the repo then submitting a PR from your own branch if you haven't done so

**Comment by sagar-io** [comment]
> 

Alright @rolewest !

**Comment by sagar-io** [comment]
Hey @rolewest, Please first Assign me and then merge the PR
